-- MySQL Script generated by MySQL Workbench
-- Mon Jul  3 12:37:48 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kadrovoe_agentstvo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kadrovoe_agentstvo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kadrovoe_agentstvo` DEFAULT CHARACTER SET utf8 ;
USE `kadrovoe_agentstvo` ;

-- -----------------------------------------------------
-- Table `kadrovoe_agentstvo`.`Rabotodateli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kadrovoe_agentstvo`.`Rabotodateli` (
  `id` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `Rabotodatel_Name` VARCHAR(45) NULL,
  `Otvetstvennoe_litso` VARCHAR(45) NULL,
  `Adres` VARCHAR(45) NULL,
  `Phone_number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kadrovoe_agentstvo`.`Obrazovanie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kadrovoe_agentstvo`.`Obrazovanie` (
  `id` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `Obrazovanie_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kadrovoe_agentstvo`.`Soiskateli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kadrovoe_agentstvo`.`Soiskateli` (
  `id` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `Soiskatel_name` VARCHAR(45) NULL,
  `Data_roghdeniya` VARCHAR(45) NULL,
  `Pol` VARCHAR(45) NULL,
  `Adres` VARCHAR(45) NULL,
  `Phone_number` VARCHAR(45) NULL,
  `Obrazovanie_id` INT UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Soiskateli_Obrazovanie1_idx` (`Obrazovanie_id` ASC),
  CONSTRAINT `fk_Soiskateli_Obrazovanie1`
    FOREIGN KEY (`Obrazovanie_id`)
    REFERENCES `kadrovoe_agentstvo`.`Obrazovanie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kadrovoe_agentstvo`.`Profession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kadrovoe_agentstvo`.`Profession` (
  `id` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `Profession_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kadrovoe_agentstvo`.`Vakansii`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kadrovoe_agentstvo`.`Vakansii` (
  `id` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `Data_open` VARCHAR(45) NULL,
  `Data_close` VARCHAR(45) NULL,
  `Opit` VARCHAR(45) NULL,
  `Zarabotannaya_plata` VARCHAR(45) NULL,
  `Adres` VARCHAR(45) NULL,
  `Obyazannosti` VARCHAR(45) NULL,
  `Trebovaniya` VARCHAR(45) NULL,
  `Rabotodateli_id` INT UNSIGNED ZEROFILL NOT NULL,
  `Profession_id` INT UNSIGNED ZEROFILL NOT NULL,
  `Obrazovanie_id` INT UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Vakansii_Rabotodateli_idx` (`Rabotodateli_id` ASC),
  INDEX `fk_Vakansii_Profession1_idx` (`Profession_id` ASC),
  INDEX `fk_Vakansii_Obrazovanie1_idx` (`Obrazovanie_id` ASC),
  CONSTRAINT `fk_Vakansii_Rabotodateli`
    FOREIGN KEY (`Rabotodateli_id`)
    REFERENCES `kadrovoe_agentstvo`.`Rabotodateli` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vakansii_Profession1`
    FOREIGN KEY (`Profession_id`)
    REFERENCES `kadrovoe_agentstvo`.`Profession` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vakansii_Obrazovanie1`
    FOREIGN KEY (`Obrazovanie_id`)
    REFERENCES `kadrovoe_agentstvo`.`Obrazovanie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
